[build]
builder = "NIXPACKS"
# This is the magic line that tells Nixpacks to look inside /backend
root = "backend"

[deploy]
# Since 'root' is set to backend, we don't need 'cd backend' anymore
startCommand = "PYTHONPATH=. uvicorn app.main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
healthCheckPath = "/api/health"
healthCheckTimeout = 100

[deploy.env]
PYTHONPATH = "."