import React, { useState } from 'react';
import { Save, RefreshCw, Check, ArrowLeft } from 'lucide-react';

interface ExtractionData {
  client_type?: string;
  portfolio_sentiment?: string;
  flight_risk?: string;
  macro_concerns?: string[];
  next_steps?: string;
  extensive_notes?: string;
}

interface ReviewSummaryProps {
  data: ExtractionData;
  onBack: () => void;
  onPushToCRM: (finalData: ExtractionData, summary: string) => Promise<void>;
}

export default function ReviewSummary({ data, onBack, onPushToCRM }: ReviewSummaryProps) {
  const [formData, setFormData] = useState<ExtractionData>(data);
  const [summary, setSummary] = useState<string>("Drafting summary...");
  const [isPushing, setIsPushing] = useState(false);
  const [isSuccess, setIsSuccess] = useState(false);

  // Synchronize the summary whenever formData changes
  React.useEffect(() => {
    const sentiment = formData.portfolio_sentiment?.toUpperCase() || 'NEUTRAL';
    const risk = formData.flight_risk?.toUpperCase() || 'UNCLEAR';
    const steps = formData.next_steps || 'To be determined';
    const notes = formData.extensive_notes || 'No detailed analysis provided.';
    
    const markdown = `# DEBRIEF SUMMARY: PROJECT ANALYSIS

## 1. STRATEGIC OVERVIEW
**Sentiment:** ${sentiment}
**Risk Level:** ${risk}

## 2. EXTENSIVE ANALYTICAL NOTES
${notes}

## 3. KEY MACRO CONCERNS
${formData.macro_concerns?.map(c => `- ${c}`).join('\n') || '- None recorded'}

## 4. CRITICAL NEXT STEPS
${steps}

---
*Generated by RIG Sales Assistant*`;

    setSummary(markdown);
  }, [formData]);


  const handleChange = (field: keyof ExtractionData, value: string) => {
    setFormData(prev => ({
       ...prev,
       [field]: field === 'macro_concerns' ? value.split(',').map(s => s.trim()) : value
    }));
  };

  const handlePush = async () => {
    setIsPushing(true);
    await onPushToCRM(formData, summary);
    setIsPushing(false);
    setIsSuccess(true);
  };

  if (isSuccess) {
    return (
      <div className="flex flex-col items-center justify-center h-full max-w-2xl mx-auto p-12 text-center">
        <div className="w-20 h-20 bg-green-500/20 text-green-500 rounded-full flex items-center justify-center mb-6">
           <Check className="w-10 h-10" />
        </div>
        <h2 className="text-3xl font-bold mb-4">Successfully Synced!</h2>
        <p className="text-slate-400 mb-8">The debrief notes and structured data have been pushed to the CRM.</p>
        <button 
          onClick={() => window.location.reload()}
          className="px-6 py-3 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl font-medium transition-colors"
        >
          Start New Debrief
        </button>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full max-w-5xl mx-auto w-full p-8 overflow-y-auto">
      <div className="flex items-center gap-4 mb-8">
         <button onClick={onBack} className="p-2 hover:bg-slate-800 rounded-lg text-slate-400">
           <ArrowLeft className="w-5 h-5" />
         </button>
        <h2 className="text-2xl font-bold">Review & Sync CRM</h2>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 h-full">
        <div className="space-y-6">
          <div className="bg-slate-800/50 rounded-2xl p-6 border border-slate-700">
            <h3 className="text-lg font-medium mb-4 text-slate-200">Structured Data</h3>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-slate-400 mb-1">Client Type</label>
                <input 
                  type="text" 
                  value={formData.client_type || ''} 
                  onChange={(e) => handleChange('client_type', e.target.value)}
                  className="w-full bg-slate-900 border border-slate-700 rounded-lg px-4 py-2 text-white focus:outline-none focus:border-indigo-500 transition-colors"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-400 mb-1">Sentiment</label>
                <input 
                  type="text" 
                  value={formData.portfolio_sentiment || ''} 
                  onChange={(e) => handleChange('portfolio_sentiment', e.target.value)}
                  className="w-full bg-slate-900 border border-slate-700 rounded-lg px-4 py-2 text-white focus:outline-none focus:border-indigo-500 transition-colors"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-400 mb-1">Flight Risk</label>
                <input 
                  type="text" 
                  value={formData.flight_risk || ''} 
                  onChange={(e) => handleChange('flight_risk', e.target.value)}
                  className="w-full bg-slate-900 border border-slate-700 rounded-lg px-4 py-2 text-white focus:outline-none focus:border-indigo-500 transition-colors"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-400 mb-1">Macro Concerns (comma separated)</label>
                <input 
                  type="text" 
                  value={formData.macro_concerns?.join(', ') || ''} 
                  onChange={(e) => handleChange('macro_concerns', e.target.value)}
                  className="w-full bg-slate-900 border border-slate-700 rounded-lg px-4 py-2 text-white focus:outline-none focus:border-indigo-500 transition-colors"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-400 mb-1">Next Steps</label>
                <textarea 
                  value={formData.next_steps || ''} 
                  onChange={(e) => handleChange('next_steps', e.target.value)}
                  className="w-full bg-slate-900 border border-slate-700 rounded-lg px-4 py-2 text-white h-20 resize-none focus:outline-none focus:border-indigo-500 transition-colors text-sm"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-400 mb-1">Analytical Notes (Strategic Depth)</label>
                <textarea 
                  value={formData.extensive_notes || ''} 
                  onChange={(e) => handleChange('extensive_notes', e.target.value)}
                  className="w-full bg-slate-900 border border-slate-700 rounded-lg px-4 py-2 text-white h-48 resize-none focus:outline-none focus:border-indigo-500 transition-colors text-sm"
                  placeholder="Gemini's detailed analysis will appear here..."
                />
              </div>
            </div>
          </div>
        </div>

        <div className="flex flex-col space-y-4">
          <div className="flex-1 bg-slate-800/50 rounded-2xl p-6 border border-slate-700 flex flex-col">
            <h3 className="text-lg font-medium mb-4 text-slate-200">Generated Summary</h3>
            <textarea
              value={summary}
              onChange={(e) => setSummary(e.target.value)}
              className="w-full flex-1 bg-slate-900 border border-slate-700 rounded-lg px-4 py-4 text-white resize-none font-mono text-sm focus:outline-none focus:border-indigo-500 transition-colors"
            />
          </div>
          
          <button
            onClick={handlePush}
            disabled={isPushing}
            className="w-full py-4 bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-500 hover:to-purple-500 text-white rounded-xl font-medium shadow-lg hover:shadow-indigo-500/25 transition-all text-lg flex items-center justify-center gap-2"
          >
            {isPushing ? <RefreshCw className="w-5 h-5 animate-spin" /> : <Save className="w-5 h-5" />}
            {isPushing ? 'Syncing...' : 'Push to CRM'}
          </button>
        </div>
      </div>
    </div>
  );
}
