import React, { useState } from 'react';
import { Save, RefreshCw, Check, ArrowLeft, FileText, TrendingUp, AlertTriangle, Navigation, User, Brain, ClipboardCheck, Zap, Cpu, Droplets, Eye, Pencil, Copy, CheckCheck } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import ReactMarkdown from 'react-markdown';

interface ExtractionData {
  client_type?: string;
  portfolio_sentiment?: string;
  flight_risk?: string;
  macro_concerns?: string[];
  next_steps?: string;
  extensive_notes?: string;
  // GQG Leadership Priority Topics
  us_equity_etf_interest?: string;
  intl_em_interest?: string;
  alpha_badger_mention?: string;
  tech_approach_interest?: string;
  ai_outlook_discussed?: string;
  oil_energy_discussed?: string;
}

interface ReviewSummaryProps {
  data: ExtractionData;
  onBack: () => void;
  onPushToCRM: (finalData: ExtractionData, summary: string) => Promise<void>;
}

const FieldInput = ({ label, icon, value, onChange, multiline = false, rows = 3, placeholder = '' }: {
  label: string;
  icon: React.ReactNode;
  value: string;
  onChange: (v: string) => void;
  multiline?: boolean;
  rows?: number;
  placeholder?: string;
}) => (
  <div className="space-y-2">
    <label className="flex items-center gap-2 text-xs font-semibold uppercase tracking-widest" style={{ color: 'var(--text-muted)' }}>
      <span style={{ color: '#6366f1' }}>{icon}</span>
      {label}
    </label>
    {multiline ? (
      <textarea
        value={value}
        onChange={e => onChange(e.target.value)}
        rows={rows}
        placeholder={placeholder}
        className="w-full resize-none rounded-xl px-4 py-3 text-sm transition-all outline-none font-['Inter']"
        style={{ background: 'rgba(6,8,15,0.8)', border: '1px solid rgba(255,255,255,0.07)', color: 'var(--text-primary)', lineHeight: '1.6' }}
        onFocus={e => { e.target.style.borderColor = 'rgba(99,102,241,0.5)'; e.target.style.boxShadow = '0 0 0 3px rgba(99,102,241,0.08)'; }}
        onBlur={e => { e.target.style.borderColor = 'rgba(255,255,255,0.07)'; e.target.style.boxShadow = 'none'; }}
      />
    ) : (
      <input
        type="text"
        value={value}
        onChange={e => onChange(e.target.value)}
        placeholder={placeholder}
        className="w-full rounded-xl px-4 py-3 text-sm transition-all outline-none font-['Inter']"
        style={{ background: 'rgba(6,8,15,0.8)', border: '1px solid rgba(255,255,255,0.07)', color: 'var(--text-primary)' }}
        onFocus={e => { e.target.style.borderColor = 'rgba(99,102,241,0.5)'; e.target.style.boxShadow = '0 0 0 3px rgba(99,102,241,0.08)'; }}
        onBlur={e => { e.target.style.borderColor = 'rgba(255,255,255,0.07)'; e.target.style.boxShadow = 'none'; }}
      />
    )}
  </div>
);

const SectionDivider = ({ label }: { label: string }) => (
  <div className="flex items-center gap-3 pt-2">
    <div className="h-px flex-1" style={{ background: 'rgba(255,255,255,0.06)' }} />
    <span className="text-[9px] font-bold uppercase tracking-widest px-2" style={{ color: 'var(--text-muted)' }}>{label}</span>
    <div className="h-px flex-1" style={{ background: 'rgba(255,255,255,0.06)' }} />
  </div>
);

const buildSummary = (f: ExtractionData): string => {
  const na = (v?: string) => v || '_Not discussed_';
  const naList = (v?: string[]) => v?.length ? v.map(c => `- ${c}`).join('\n') : '- None recorded';
  const gqgLine = (label: string, val?: string) =>
    `- **${label}:** ${val || '_Not covered_'}`;

  return `# GQG Partners — Client Debrief Summary
*Generated by Shunya Note Buddy*

---

## 1. Client Profile

**Client Type:** ${na(f.client_type)}

**Portfolio Sentiment:** ${na(f.portfolio_sentiment)}

**Flight Risk:** ${na(f.flight_risk)}

---

## 2. Macro Concerns

${naList(f.macro_concerns)}

---

## 3. GQG Leadership Priority Coverage

${gqgLine('US Equity ETF Interest', f.us_equity_etf_interest)}
${gqgLine('Intl / EM Interest', f.intl_em_interest)}
${gqgLine('Alpha Badger Mention', f.alpha_badger_mention)}
${gqgLine("GQG Tech Approach Interest", f.tech_approach_interest)}
${gqgLine("GQG's Outlook on AI", f.ai_outlook_discussed)}
${gqgLine("GQG's View on Oil & Energy", f.oil_energy_discussed)}

---

## 4. Extensive Analytical Notes

${f.extensive_notes || '_No detailed notes recorded._'}

---

## 5. Next Steps & Action Items

${na(f.next_steps)}

---

*Shunya Note Buddy · GQG Partners Sales Intelligence*`;
};

export default function ReviewSummary({ data, onBack, onPushToCRM }: ReviewSummaryProps) {
  const [formData, setFormData] = useState<ExtractionData>(data);
  const [summary, setSummary] = useState<string>(() => buildSummary(data));
  const [isPushing, setIsPushing] = useState(false);
  const [isSuccess, setIsSuccess] = useState(false);
  const [isEditingNote, setIsEditingNote] = useState(false);
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Regenerate summary whenever form data changes
  React.useEffect(() => {
    setSummary(buildSummary(formData));
  }, [formData]);

  const handleChange = (field: keyof ExtractionData, value: string) => {
    setFormData(prev => ({
      ...prev,
      [field]: field === 'macro_concerns' ? value.split(',').map(s => s.trim()) : value
    }));
  };

  const handlePush = async () => {
    setIsPushing(true);
    await onPushToCRM(formData, summary);
    setIsPushing(false);
    setIsSuccess(true);
  };

  // ── Success screen ─────────────────────────────────────────────────────────
  if (isSuccess) {
    return (
      <div className="h-full flex flex-col items-center justify-center p-12 text-center">
        <motion.div initial={{ scale: 0 }} animate={{ scale: 1 }} transition={{ type: 'spring', stiffness: 300, damping: 20 }}>
          <div className="relative w-24 h-24 mx-auto mb-8">
            <div className="absolute inset-0 rounded-full" style={{ background: 'radial-gradient(circle, rgba(16,185,129,0.3) 0%, transparent 70%)', filter: 'blur(16px)' }} />
            <div className="relative w-24 h-24 rounded-full flex items-center justify-center"
              style={{ background: 'rgba(16,185,129,0.15)', border: '2px solid rgba(16,185,129,0.4)' }}>
              <Check className="w-10 h-10 text-emerald-400" strokeWidth={2.5} />
            </div>
          </div>
        </motion.div>
        <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}>
          <h2 className="text-3xl font-bold mb-3 font-['Space_Grotesk']"><span className="text-gradient">Synced to CRM</span></h2>
          <p className="text-sm mb-8 max-w-sm leading-relaxed" style={{ color: 'var(--text-secondary)' }}>
            All debrief notes and structured data have been successfully pushed to the CRM system.
          </p>
          <button onClick={() => window.location.reload()}
            className="px-8 py-3.5 rounded-2xl font-semibold text-sm transition-all"
            style={{ background: 'linear-gradient(135deg, #6366f1, #8b5cf6)', color: 'white', boxShadow: '0 4px 24px rgba(99,102,241,0.35)' }}>
            Start New Debrief
          </button>
        </motion.div>
      </div>
    );
  }

  return (
    <div className="h-full flex flex-col overflow-hidden">
      {/* Header */}
      <div className="flex items-center gap-4 px-8 py-5 shrink-0" style={{ borderBottom: '1px solid var(--border-subtle)' }}>
        <button onClick={onBack} className="p-2 rounded-xl transition-all"
          style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid var(--border-subtle)' }}>
          <ArrowLeft className="w-4 h-4" style={{ color: 'var(--text-secondary)' }} />
        </button>
        <div>
          <h2 className="text-lg font-bold font-['Space_Grotesk']">Review & Sync CRM</h2>
          <p className="text-xs mt-0.5" style={{ color: 'var(--text-muted)' }}>Verify all extracted data before pushing</p>
        </div>
        <div className="ml-auto flex items-center gap-2">
          <ClipboardCheck className="w-4 h-4 text-indigo-400" />
          <span className="text-xs font-medium text-indigo-400">Final Review</span>
        </div>
      </div>

      {/* Two-column layout */}
      <div className="flex-1 overflow-hidden flex">

        {/* Left: Structured Data — scrollable */}
        <div className="flex-1 overflow-y-auto scrollbar-hide p-8 space-y-5" style={{ borderRight: '1px solid var(--border-subtle)' }}>

          <SectionDivider label="Standard CRM" />

          <FieldInput label="Client Type" icon={<User className="w-3.5 h-3.5" />}
            value={formData.client_type || ''} onChange={v => handleChange('client_type', v)} placeholder="Retail or Institutional" />
          <FieldInput label="Portfolio Sentiment" icon={<TrendingUp className="w-3.5 h-3.5" />}
            value={formData.portfolio_sentiment || ''} onChange={v => handleChange('portfolio_sentiment', v)} placeholder="Client's feeling on portfolio" />
          <FieldInput label="Flight Risk" icon={<AlertTriangle className="w-3.5 h-3.5" />}
            value={formData.flight_risk || ''} onChange={v => handleChange('flight_risk', v)} placeholder="Low / Medium / High" />
          <FieldInput label="Macro Concerns (comma separated)" icon={<FileText className="w-3.5 h-3.5" />}
            value={formData.macro_concerns?.join(', ') || ''} onChange={v => handleChange('macro_concerns', v)} placeholder="inflation, rate hikes..." />
          <FieldInput label="Next Steps" icon={<Navigation className="w-3.5 h-3.5" />}
            value={formData.next_steps || ''} onChange={v => handleChange('next_steps', v)}
            multiline rows={3} placeholder="Follow-up actions..." />

          <SectionDivider label="GQG Leadership Priorities" />

          <FieldInput label="US Equity ETF Interest" icon={<Zap className="w-3.5 h-3.5" />}
            value={formData.us_equity_etf_interest || ''} onChange={v => handleChange('us_equity_etf_interest', v)}
            placeholder="Highly interested / Not discussed / Skeptical..." />
          <FieldInput label="Intl / EM Interest" icon={<TrendingUp className="w-3.5 h-3.5" />}
            value={formData.intl_em_interest || ''} onChange={v => handleChange('intl_em_interest', v)}
            placeholder="Open to exploring / Not interested..." />
          <FieldInput label="Alpha Badger Mention" icon={<FileText className="w-3.5 h-3.5" />}
            value={formData.alpha_badger_mention || ''} onChange={v => handleChange('alpha_badger_mention', v)}
            placeholder="Mentioned positively / Not raised..." />
          <FieldInput label="GQG Tech Approach Interest" icon={<Cpu className="w-3.5 h-3.5" />}
            value={formData.tech_approach_interest || ''} onChange={v => handleChange('tech_approach_interest', v)}
            placeholder="Intrigued / Neutral / Not discussed..." />
          <FieldInput label="GQG's AI Outlook Discussed" icon={<Brain className="w-3.5 h-3.5" />}
            value={formData.ai_outlook_discussed || ''} onChange={v => handleChange('ai_outlook_discussed', v)}
            placeholder="Yes — client was receptive / Not discussed..." />
          <FieldInput label="GQG's Oil & Energy View Discussed" icon={<Droplets className="w-3.5 h-3.5" />}
            value={formData.oil_energy_discussed || ''} onChange={v => handleChange('oil_energy_discussed', v)}
            placeholder="Yes — expressed concerns / Not raised..." />

          <SectionDivider label="Analyst Notes" />

          <FieldInput label="Extensive Analytical Notes" icon={<Brain className="w-3.5 h-3.5" />}
            value={formData.extensive_notes || ''} onChange={v => handleChange('extensive_notes', v)}
            multiline rows={8} placeholder="Gemini's detailed analysis will appear here..." />
        </div>

        {/* Right: Generated Summary — scrollable */}
        <div className="flex-1 flex flex-col p-8">
          {/* Summary header with toggle */}
          <div className="flex items-center gap-2 mb-4 shrink-0">
            <div className="w-6 h-6 rounded-lg flex items-center justify-center"
              style={{ background: 'rgba(139,92,246,0.15)', border: '1px solid rgba(139,92,246,0.2)' }}>
              <Brain className="w-3.5 h-3.5 text-purple-400" />
            </div>
            <h3 className="text-sm font-bold" style={{ color: 'var(--text-primary)' }}>Generated Summary</h3>

            <div className="ml-auto flex items-center gap-2">
              {/* Copy button */}
              <button
                onClick={handleCopy}
                className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-xs font-medium transition-all"
                style={{ background: 'rgba(255,255,255,0.04)', border: '1px solid var(--border-subtle)', color: copied ? '#6ee7b7' : 'var(--text-muted)' }}
              >
                {copied ? <CheckCheck className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                {copied ? 'Copied!' : 'Copy'}
              </button>

              {/* Preview / Edit toggle */}
              <div className="flex rounded-lg overflow-hidden" style={{ border: '1px solid var(--border-subtle)' }}>
                <button
                  onClick={() => setIsEditingNote(false)}
                  className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold transition-all"
                  style={{
                    background: !isEditingNote ? 'rgba(99,102,241,0.2)' : 'transparent',
                    color: !isEditingNote ? '#a5b4fc' : 'var(--text-muted)',
                    borderRight: '1px solid var(--border-subtle)',
                  }}>
                  <Eye className="w-3 h-3" /> Preview
                </button>
                <button
                  onClick={() => setIsEditingNote(true)}
                  className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold transition-all"
                  style={{
                    background: isEditingNote ? 'rgba(99,102,241,0.2)' : 'transparent',
                    color: isEditingNote ? '#a5b4fc' : 'var(--text-muted)',
                  }}>
                  <Pencil className="w-3 h-3" /> Edit
                </button>
              </div>
            </div>
          </div>

          {/* Summary content area */}
          <div className="flex-1 relative min-h-[400px] rounded-2xl overflow-hidden"
            style={{ background: 'rgba(6,8,15,0.9)', border: '1px solid rgba(255,255,255,0.06)' }}>
            <AnimatePresence mode="wait">
              {isEditingNote ? (
                <motion.textarea
                  key="edit"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  value={summary}
                  onChange={e => setSummary(e.target.value)}
                  className="absolute inset-0 w-full h-full resize-none p-5 text-xs font-mono leading-relaxed outline-none"
                  style={{
                    background: 'transparent',
                    color: '#94a3b8',
                    lineHeight: '1.8',
                  }}
                />
              ) : (
                <motion.div
                  key="preview"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  className="absolute inset-0 overflow-y-auto scrollbar-hide p-6 prose-summary"
                >
                  <ReactMarkdown
                    components={{
                      h1: ({ children }) => (
                        <h1 style={{ color: '#e0e7ff', fontSize: '15px', fontWeight: 800, marginBottom: '4px', fontFamily: 'Space Grotesk, sans-serif', letterSpacing: '-0.01em' }}>{children}</h1>
                      ),
                      h2: ({ children }) => (
                        <h2 style={{ color: '#a5b4fc', fontSize: '11px', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.12em', marginTop: '20px', marginBottom: '8px', borderBottom: '1px solid rgba(99,102,241,0.2)', paddingBottom: '6px' }}>{children}</h2>
                      ),
                      h3: ({ children }) => (
                        <h3 style={{ color: '#c4b5fd', fontSize: '11px', fontWeight: 600, marginTop: '12px', marginBottom: '4px' }}>{children}</h3>
                      ),
                      p: ({ children }) => (
                        <p style={{ color: '#94a3b8', fontSize: '12px', lineHeight: '1.8', marginBottom: '8px' }}>{children}</p>
                      ),
                      strong: ({ children }) => (
                        <strong style={{ color: '#cbd5e1', fontWeight: 600 }}>{children}</strong>
                      ),
                      ul: ({ children }) => (
                        <ul style={{ paddingLeft: '16px', marginBottom: '8px', listStyleType: 'disc' }}>{children}</ul>
                      ),
                      li: ({ children }) => (
                        <li style={{ color: '#94a3b8', fontSize: '12px', lineHeight: '1.8', marginBottom: '2px' }}>{children}</li>
                      ),
                      hr: () => (
                        <hr style={{ border: 'none', borderTop: '1px solid rgba(255,255,255,0.06)', margin: '16px 0' }} />
                      ),
                      code: ({ children }) => (
                        <code style={{ background: 'rgba(99,102,241,0.1)', color: '#a5b4fc', padding: '1px 6px', borderRadius: '4px', fontSize: '11px', fontFamily: 'monospace' }}>{children}</code>
                      ),
                    }}
                  >
                    {summary}
                  </ReactMarkdown>
                </motion.div>
              )}
            </AnimatePresence>
          </div>

          <motion.button
            onClick={handlePush}
            disabled={isPushing}
            whileTap={{ scale: 0.98 }}
            className="w-full py-4 rounded-2xl font-semibold text-base flex items-center justify-center gap-3 mt-5 transition-all shrink-0"
            style={{
              background: isPushing ? 'rgba(99,102,241,0.2)' : 'linear-gradient(135deg, #6366f1 0%, #7c3aed 100%)',
              color: isPushing ? '#6366f1' : 'white',
              boxShadow: isPushing ? 'none' : '0 4px 32px rgba(99,102,241,0.4)',
              border: '1px solid rgba(99,102,241,0.3)',
            }}>
            {isPushing ? <><RefreshCw className="w-5 h-5 animate-spin" />Syncing...</> : <><Save className="w-5 h-5" />Push to CRM</>}
          </motion.button>
        </div>
      </div>
    </div>
  );
}
