import React, { useState } from 'react';
import { Save, RefreshCw, Check, ArrowLeft, FileText, TrendingUp, AlertTriangle, Navigation, User, Brain, ClipboardCheck } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

interface ExtractionData {
  client_type?: string;
  portfolio_sentiment?: string;
  flight_risk?: string;
  macro_concerns?: string[];
  next_steps?: string;
  extensive_notes?: string;
}

interface ReviewSummaryProps {
  data: ExtractionData;
  onBack: () => void;
  onPushToCRM: (finalData: ExtractionData, summary: string) => Promise<void>;
}

const FieldInput = ({ label, icon, value, onChange, multiline = false, rows = 3, placeholder = '' }: {
  label: string;
  icon: React.ReactNode;
  value: string;
  onChange: (v: string) => void;
  multiline?: boolean;
  rows?: number;
  placeholder?: string;
}) => (
  <div className="space-y-2">
    <label className="flex items-center gap-2 text-xs font-semibold uppercase tracking-widest" style={{ color: 'var(--text-muted)' }}>
      <span style={{ color: '#6366f1' }}>{icon}</span>
      {label}
    </label>
    {multiline ? (
      <textarea
        value={value}
        onChange={e => onChange(e.target.value)}
        rows={rows}
        placeholder={placeholder}
        className="w-full resize-none rounded-xl px-4 py-3 text-sm transition-all outline-none font-['Inter']"
        style={{
          background: 'rgba(6,8,15,0.8)',
          border: '1px solid rgba(255,255,255,0.07)',
          color: 'var(--text-primary)',
          lineHeight: '1.6',
        }}
        onFocus={e => { e.target.style.borderColor = 'rgba(99,102,241,0.5)'; e.target.style.boxShadow = '0 0 0 3px rgba(99,102,241,0.08)'; }}
        onBlur={e => { e.target.style.borderColor = 'rgba(255,255,255,0.07)'; e.target.style.boxShadow = 'none'; }}
      />
    ) : (
      <input
        type="text"
        value={value}
        onChange={e => onChange(e.target.value)}
        placeholder={placeholder}
        className="w-full rounded-xl px-4 py-3 text-sm transition-all outline-none font-['Inter']"
        style={{
          background: 'rgba(6,8,15,0.8)',
          border: '1px solid rgba(255,255,255,0.07)',
          color: 'var(--text-primary)',
        }}
        onFocus={e => { e.target.style.borderColor = 'rgba(99,102,241,0.5)'; e.target.style.boxShadow = '0 0 0 3px rgba(99,102,241,0.08)'; }}
        onBlur={e => { e.target.style.borderColor = 'rgba(255,255,255,0.07)'; e.target.style.boxShadow = 'none'; }}
      />
    )}
  </div>
);

export default function ReviewSummary({ data, onBack, onPushToCRM }: ReviewSummaryProps) {
  const [formData, setFormData] = useState<ExtractionData>(data);
  const [summary, setSummary] = useState<string>('');
  const [isPushing, setIsPushing] = useState(false);
  const [isSuccess, setIsSuccess] = useState(false);

  React.useEffect(() => {
    const sentiment = formData.portfolio_sentiment?.toUpperCase() || 'NEUTRAL';
    const risk = formData.flight_risk?.toUpperCase() || 'UNCLEAR';
    const steps = formData.next_steps || 'To be determined';
    const notes = formData.extensive_notes || 'No detailed analysis provided.';

    const markdown = `# DEBRIEF SUMMARY\n\n## 1. STRATEGIC OVERVIEW\n**Client Type:** ${formData.client_type || 'N/A'}\n**Sentiment:** ${sentiment}\n**Flight Risk:** ${risk}\n\n## 2. ANALYTICAL NOTES\n${notes}\n\n## 3. KEY MACRO CONCERNS\n${formData.macro_concerns?.map(c => `- ${c}`).join('\n') || '- None recorded'}\n\n## 4. NEXT STEPS\n${steps}\n\n---\n*Generated by Shunya Note Buddy*`;
    setSummary(markdown);
  }, [formData]);

  const handleChange = (field: keyof ExtractionData, value: string) => {
    setFormData(prev => ({
      ...prev,
      [field]: field === 'macro_concerns' ? value.split(',').map(s => s.trim()) : value
    }));
  };

  const handlePush = async () => {
    setIsPushing(true);
    await onPushToCRM(formData, summary);
    setIsPushing(false);
    setIsSuccess(true);
  };

  if (isSuccess) {
    return (
      <div className="h-full flex flex-col items-center justify-center p-12 text-center">
        <motion.div initial={{ scale: 0 }} animate={{ scale: 1 }} transition={{ type: 'spring', stiffness: 300, damping: 20 }}>
          <div className="relative w-24 h-24 mx-auto mb-8">
            {/* Success glow */}
            <div className="absolute inset-0 rounded-full"
              style={{ background: 'radial-gradient(circle, rgba(16,185,129,0.3) 0%, transparent 70%)', filter: 'blur(16px)' }} />
            <div className="relative w-24 h-24 rounded-full flex items-center justify-center"
              style={{ background: 'rgba(16,185,129,0.15)', border: '2px solid rgba(16,185,129,0.4)' }}>
              <Check className="w-10 h-10 text-emerald-400" strokeWidth={2.5} />
            </div>
          </div>
        </motion.div>
        <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}>
          <h2 className="text-3xl font-bold mb-3 font-['Space_Grotesk']">
            <span className="text-gradient">Synced to CRM</span>
          </h2>
          <p className="text-sm mb-8 max-w-sm leading-relaxed" style={{ color: 'var(--text-secondary)' }}>
            All debrief notes and structured data have been successfully pushed to the CRM system.
          </p>
          <button
            onClick={() => window.location.reload()}
            className="px-8 py-3.5 rounded-2xl font-semibold text-sm transition-all"
            style={{
              background: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
              color: 'white',
              boxShadow: '0 4px 24px rgba(99,102,241,0.35)'
            }}
          >
            Start New Debrief
          </button>
        </motion.div>
      </div>
    );
  }

  return (
    <div className="h-full flex flex-col overflow-hidden">
      {/* Header */}
      <div className="flex items-center gap-4 px-8 py-5 shrink-0" style={{ borderBottom: '1px solid var(--border-subtle)' }}>
        <button onClick={onBack}
          className="p-2 rounded-xl transition-all"
          style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid var(--border-subtle)' }}>
          <ArrowLeft className="w-4 h-4" style={{ color: 'var(--text-secondary)' }} />
        </button>
        <div>
          <h2 className="text-lg font-bold font-['Space_Grotesk']">Review & Sync CRM</h2>
          <p className="text-xs mt-0.5" style={{ color: 'var(--text-muted)' }}>
            Verify extracted data before pushing to CRM
          </p>
        </div>
        <div className="ml-auto flex items-center gap-2">
          <ClipboardCheck className="w-4 h-4 text-indigo-400" />
          <span className="text-xs font-medium text-indigo-400">Final Review</span>
        </div>
      </div>

      {/* Two-column layout */}
      <div className="flex-1 overflow-y-auto scrollbar-hide">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-0 h-full">
          {/* Left: Structured Data */}
          <div className="p-8 space-y-5" style={{ borderRight: '1px solid var(--border-subtle)' }}>
            <div className="flex items-center gap-2 mb-6">
              <div className="w-6 h-6 rounded-lg flex items-center justify-center"
                style={{ background: 'rgba(99,102,241,0.15)', border: '1px solid rgba(99,102,241,0.2)' }}>
                <FileText className="w-3.5 h-3.5 text-indigo-400" />
              </div>
              <h3 className="text-sm font-bold" style={{ color: 'var(--text-primary)' }}>Structured Data</h3>
            </div>

            <FieldInput
              label="Client Type"
              icon={<User className="w-3.5 h-3.5" />}
              value={formData.client_type || ''}
              onChange={v => handleChange('client_type', v)}
              placeholder="Retail or Institutional"
            />
            <FieldInput
              label="Portfolio Sentiment"
              icon={<TrendingUp className="w-3.5 h-3.5" />}
              value={formData.portfolio_sentiment || ''}
              onChange={v => handleChange('portfolio_sentiment', v)}
              placeholder="Client's feeling on portfolio"
            />
            <FieldInput
              label="Flight Risk"
              icon={<AlertTriangle className="w-3.5 h-3.5" />}
              value={formData.flight_risk || ''}
              onChange={v => handleChange('flight_risk', v)}
              placeholder="Low / Medium / High"
            />
            <FieldInput
              label="Macro Concerns (comma separated)"
              icon={<FileText className="w-3.5 h-3.5" />}
              value={formData.macro_concerns?.join(', ') || ''}
              onChange={v => handleChange('macro_concerns', v)}
              placeholder="inflation, rate hikes, credit risk..."
            />
            <FieldInput
              label="Next Steps"
              icon={<Navigation className="w-3.5 h-3.5" />}
              value={formData.next_steps || ''}
              onChange={v => handleChange('next_steps', v)}
              multiline
              rows={3}
              placeholder="Follow-up actions for the sales team..."
            />
            <FieldInput
              label="Analyst Notes"
              icon={<Brain className="w-3.5 h-3.5" />}
              value={formData.extensive_notes || ''}
              onChange={v => handleChange('extensive_notes', v)}
              multiline
              rows={6}
              placeholder="Gemini's detailed analysis will appear here..."
            />
          </div>

          {/* Right: Generated Summary */}
          <div className="p-8 flex flex-col">
            <div className="flex items-center gap-2 mb-6">
              <div className="w-6 h-6 rounded-lg flex items-center justify-center"
                style={{ background: 'rgba(139,92,246,0.15)', border: '1px solid rgba(139,92,246,0.2)' }}>
                <Brain className="w-3.5 h-3.5 text-purple-400" />
              </div>
              <h3 className="text-sm font-bold" style={{ color: 'var(--text-primary)' }}>Generated Summary</h3>
              <span className="ml-auto tag tag-indigo text-[9px]">Editable</span>
            </div>

            <div className="flex-1 relative min-h-[300px]">
              <textarea
                value={summary}
                onChange={e => setSummary(e.target.value)}
                className="absolute inset-0 w-full h-full resize-none rounded-2xl p-5 text-xs font-mono leading-relaxed outline-none transition-all"
                style={{
                  background: 'rgba(6,8,15,0.9)',
                  border: '1px solid rgba(255,255,255,0.06)',
                  color: '#94a3b8',
                  lineHeight: '1.8',
                }}
                onFocus={e => { e.target.style.borderColor = 'rgba(139,92,246,0.3)'; }}
                onBlur={e => { e.target.style.borderColor = 'rgba(255,255,255,0.06)'; }}
              />
            </div>

            {/* Push button */}
            <motion.button
              onClick={handlePush}
              disabled={isPushing}
              whileTap={{ scale: 0.98 }}
              className="w-full py-4 rounded-2xl font-semibold text-base flex items-center justify-center gap-3 mt-5 transition-all"
              style={{
                background: isPushing
                  ? 'rgba(99,102,241,0.2)'
                  : 'linear-gradient(135deg, #6366f1 0%, #7c3aed 100%)',
                color: isPushing ? '#6366f1' : 'white',
                boxShadow: isPushing ? 'none' : '0 4px 32px rgba(99,102,241,0.4), 0 1px 2px rgba(0,0,0,0.5)',
                border: '1px solid rgba(99,102,241,0.3)',
              }}
            >
              {isPushing ? (
                <>
                  <RefreshCw className="w-5 h-5 animate-spin" />
                  Syncing to CRM...
                </>
              ) : (
                <>
                  <Save className="w-5 h-5" />
                  Push to CRM
                </>
              )}
            </motion.button>
          </div>
        </div>
      </div>
    </div>
  );
}
